### ISSUE TITLE
Error when automation run

### ISSUE THREAD

**Issue by hellcry37** [basschipper/homeassistant-generic-hygrostat#42]
ha on docker latest 2022.10

```txt
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/generic_hygrostat/binary_sensor.py:188
Integration: generic_hygrostat (documentation)
First occurred: 29 October 2022 at 08:16:11 (449 occurrences)
Last logged: 20:36:12

Error doing job: Exception in callback async_track_point_in_utc_time.<locals>.run_action(<Job HassJobT...7fb69ce6dfc0>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:1303
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1318, in run_action
    hass.async_run_hass_job(job, utc_point_in_time)
  File "/usr/src/homeassistant/homeassistant/core.py", line 567, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1379, in interval_listener
    hass.async_run_hass_job(job, now)
  File "/usr/src/homeassistant/homeassistant/core.py", line 567, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/generic_hygrostat/binary_sensor.py", line 148, in _async_update
    self.update_humidity()
  File "/config/custom_components/generic_hygrostat/binary_sensor.py", line 188, in update_humidity
    self.sensor_humidity = float(sensor.attributes[self.sensor_attribute])
KeyError: 'humidity'
```

is set like this:

```txt
- platform: generic_hygrostat
  name: Bathroom Hygrostat
  sensor: sensor.bathroom_humidity # Source humidity sensor
  attribute: humidity # Optional use sensor attribute instead of state.
  delta_trigger: 3 # Optional humidity swing to detect. Default = 3
  target_offset: 3 # Optional dehumidification target offset. Default = 3
  min_on_time: 300 # Optional min on time in seconds. Default = 0 seconds
  max_on_time: 7200 # Optional safety max on time in seconds. Default = 7200 seconds
  sample_interval: 300 # Optional time between taking humidity samples in seconds, default 300 seconds
  # min_humidity: 50 # Optional minimum humidity to enable dehumidification. Default = 0
  unique_id: bathroom_hygrostat # Optional ID that uniquely identifies this sensor. Set this to a unique value to allow customization through the UI.
```
What am I doing wrong or what is to be corrected.

**Comment by nestor1832** [comment]
I have the same problem with the HA Supervisor 2022.10.2
User interface: 20221108.0 - latest

Logger: homeassistant
Source: custom_components/generic_hygrostat/binary_sensor.py:188
Integration: generic_hygrostat (documentation)
First occurred: 14 novembre 2022 à 23:32:02 (737 occurrences)
Last logged: 11:48:05

Error doing job: Exception in callback async_track_point_in_utc_time.<locals>.run_action(<Job HassJobT...t 0xb197a190>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:1301
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1316, in run_action
    hass.async_run_hass_job(job, utc_point_in_time)
  File "/usr/src/homeassistant/homeassistant/core.py", line 573, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1377, in interval_listener
    hass.async_run_hass_job(job, now)
  File "/usr/src/homeassistant/homeassistant/core.py", line 573, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/generic_hygrostat/binary_sensor.py", line 148, in _async_update
    self.update_humidity()
  File "/config/custom_components/generic_hygrostat/binary_sensor.py", line 188, in update_humidity
    self.sensor_humidity = float(sensor.attributes[self.sensor_attribute])
KeyError: 'humidity'

**Comment by basschipper** [comment]
As the error explains, your sensor doesn't have a humidity attribute.
Double check your sensors attributes.
For instance by using the developer template tool and check:

`{{ states.sensor.bathroom_humidity.attributes['humidity'] }}`

**Comment by hellcry37** [comment]
but the hole sensor is a humidity sensor, why it needs an attribute if the state of the sensor gives humidity?

**Comment by hellcry37** [comment]
ahh correction i might be added "attribute: humidity # Optional use sensor attribute instead of state." by mistake, i'll check now

**Comment by hellcry37** [comment]
It is very clear now, I am a f**g nub. Thank you and sry for wasting your precious time.

Ofc it works with attribute commented!
