### ISSUE TITLE
Exception Error. 

### ISSUE THREAD

**Issue by patrickliesens** [basschipper/homeassistant-generic-hygrostat#43]
Error that comes when using the integration.  My humidity sensor is has no attribute value of humidity. The humidity value is in the state.  Is this the problem?
![Capture](https://user-images.githubusercontent.com/59433529/209828545-08518c6c-8d32-4167-b954-e8f4fb922325.PNG)

Logger: homeassistant
Source: custom_components/generic_hygrostat/binary_sensor.py:188
Integration: generic_hygrostat (documentation)
First occurred: 15:32:38 (1 occurrences)
Last logged: 15:32:38

Error doing job: Exception in callback async_track_point_in_utc_time.<locals>.run_action(<Job HassJobT...7f500e032200>>) at /usr/src/homeassistant/homeassistant/helpers/event.py:1305
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1320, in run_action
    hass.async_run_hass_job(job, utc_point_in_time)
  File "/usr/src/homeassistant/homeassistant/core.py", line 574, in async_run_hass_job
    hassjob.target(*args)
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1381, in interval_listener
    hass.async_run_hass_job(job, now)
  File "/usr/src/homeassistant/homeassistant/core.py", line 574, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/generic_hygrostat/binary_sensor.py", line 148, in _async_update
    self.update_humidity()
  File "/config/custom_components/generic_hygrostat/binary_sensor.py", line 188, in update_humidity
    self.sensor_humidity = float(sensor.attributes[self.sensor_attribute])
KeyError: 'humidity'

**Comment by basschipper** [comment]
You give the answer yourself.
So why do you configure a sensor attribute if your sensor doesn't have one?

**Comment by patrickliesens** [comment]
Good question. i'm going to fast for my level of experience. Its working now.
