### ISSUE TITLE
Python 3.13 broke the hygrostat

### ISSUE THREAD

**Issue by sammyke007** [basschipper/homeassistant-generic-hygrostat#53]
Deze fout is ontstaan door een aangepaste integratie.

Log:
```
Logger: homeassistant
Bron: custom_components/generic_hygrostat/binary_sensor.py:191
integratie: generic_hygrostat (documentatie)
Eerst voorgekomen: 11 december 2024 om 15:46:58 (200 gebeurtenissen)
Laatst gelogd: 08:21:58

Error doing job: Exception in callback _TrackTimeInterval._interval_listener() (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1660, in _interval_listener
    self.hass.async_run_hass_job(self._run_job, dt_util.utcnow(), background=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 949, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/config/custom_components/generic_hygrostat/binary_sensor.py", line 151, in _async_update
    self.update_humidity()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/generic_hygrostat/binary_sensor.py", line 191, in update_humidity
    self.sensor_humidity = float(sensor.attributes[self.sensor_attribute])
                                 ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'humidity'
```

configuration.yaml:
```
binary_sensor:
  - platform: generic_hygrostat
    name: Bathroom Hygrostat
    sensor: sensor.tmp_badkamer_humidity # Source humidity sensor
    #sensor: input_number.badkamer_humidity_helper # Source humidity sensor
    attribute: humidity # Optional use sensor attribute instead of state.
    delta_trigger: 3 # Optional humidity swing to detect. Default = 3
    target_offset: 3 # Optional dehumidification target offset. Default = 3
    min_on_time: 0 # Optional min on time in seconds. Default = 0 seconds
    max_on_time: 4500 # Optional safety max on time in seconds. Default = 7200 seconds
    sample_interval: 300 # Optional time between taking humidity samples in seconds, default 300 seconds
    min_humidity: 30 # Optional minimum humidity to enable dehumidification. Default = 0
    unique_id: bathroom_hygrostat # Optional ID that uniquely identifies this sensor. Set this to a unique value to allow customization through the UI.
```

**Comment by sammyke007** [comment]
Hmmm... I don't know whether my config got changed by accident or my humidity sensor changed from attribute to state, but I think it's fixed by commenting
**#attribute: humidity # Optional use sensor attribute instead of state.**
and rebooting Home Assistant.
I'll close it when I'm 100% sure later today. Sorry!

**Comment by sammyke007** [comment]
Mistake on my side, closing!
